# log levels: debug | info | warn | error
loglevel = "debug"

[domoticz]
  url = "http://<USER>:<PASSWORD>@<HOSTNAME>:8080"
  hardwareID = 3 # dummy hardware idx

# sensor names: temperature | humidity | light | motion | low_battery | vcc
[[devices]]
  id = 2
  room = "kitchen"

  [[devices.sensors]]
    name = "temperature"
    correction = -0.2
    domoticz = 2 # virtual device idx for temperature and humidity

  [[devices.sensors]]
    name = "humidity"
    correction = -3

  [[devices.sensors]]
    name = "light"
    correction = -1
    domoticz = 3 # virtual device idx

[[devices]]
  id = 3
  room = "living_room"

  [[devices.sensors]]
    name = "temperature"
    domoticz = 4 # virtual device idx for temperature only

  [[devices.sensors]]
    name = "light"
    disable = true # disable that sensor
